# Config file for the map generator
---
# ===============================================
# Main params to modify
# ===============================================
input_image: sun.jpg
output_map_name: sun_truth.txt

# a reference map to specify the objects (how many for each type) on the map
reference_map: sunref.txt

# fruits - list of fruits to be placed in the arena and their colours
fruits:
  pear: [152, 251, 152]  # BGR
  orange: [0, 127, 255]
  apple: [0, 0, 191]
  kiwi: [0, 63, 127]
  melon: [255, 192, 203]
  melon: [255, 192, 203]
  fruit2: [0,0,0]
  fruit3: [0,0,0]
  fruit4: [0,0,0]
  fruit5: [0,0,0]
  
# change this if the GUI is too big for your screen
image_display_res:
  x: 700
  y: 450

# increase this if it is difficult to click on the objects
max_click_radius: 25  # unit: [pixels]

arena_size: # unit: [m]
  x: 3.0
  y: 3.0

# ===============================================
# less important params (recommend not to change)
# ===============================================
ArUco_block_size: 0.08  # unit: [m]
border_size: 2
grid_size: 1
reference_error_line_size: 1
object_point_size: 12
ArUco_font_size: 0.5
ArUco_font_thickness: 1
